#Workflow written by David Lagace
#For DevOps Bootcamp / January 2022

#Trigger on Push and Pull requests
name: Workflow for Capstone Project
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

#set default working directory
defaults:
  run:
    working-directory: capstone_project/hello-world    

jobs:
  job1:
    name: Checkout, Install and test
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout tasks
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

  #job2:
   # name: Build Container
    #runs-on: ubuntu-latest
    #needs: [job1 ]

    #steps:
     # - name: build-container

  push_to_registry:
    name: build-container and push to docker hub
    needs: [job1 ]  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Push to Docker Hub
        uses: docker/build-push-action@v1 # Info: https://github.com/docker/build-push-action/tree/releases/v1#tags
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKERHUB_REPOSITORY }}
          tag_with_ref: true # Info: https://github.com/docker/build-push-action/tree/releases/v1#tag_with_ref
          tag_with_sha: true # Info: https://github.com/docker/build-push-action/tree/releases/v1#tag_with_sha
          tags: latest


      

