#Workflow written by David Lagace
#For DevOps Bootcamp / January 2022

#Trigger on Push and Pull requests
name: Workflow for Capstone Project
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      env:
        CI: true
    - run: npm install
    - run: npm run test
  
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - run: npm run build --if-present
      - run: npm test



  job1:
    needs: [build-job]
    name: Checkout job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout task
        uses: actions/checkout@v2

    #job2:
     #   needs: [job1]