#Workflow written by David Lagace
#For DevOps Bootcamp / January 2022

#Trigger on Push and Pull requests
name: Workflow for Capstone Project
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

#set default working directory
defaults:
  run:
    working-directory: ./capstone_project/hello-world    

jobs:
  job1:
    name: Checkout, Install and test
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout tasks
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

  #job2:
   # name: Build Container
    #runs-on: ubuntu-latest
    #needs: [job1 ]

    #steps:
     # - name: build-container

  docker:
    needs: [job1 ]  
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKERHUB_REPOSITORY }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: mune360/mune360-bootcamp:latest


      

